import { useState } from "react";
import { api } from "../lib/api";

export default function ApplicationForm({ onNavigate }) {
  const [submitted,setSubmitted]=useState(false), [error,setError]=useState(""), [busy,setBusy]=useState(false);
  async function submit(e){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);try{await api("/api/applications",{method:"POST",body:{fullName:f.get("fullName"),facebook:f.get("facebook"),phone:f.get("phone"),occupationSchool:f.get("occupationSchool"),preferredMoveIn:f.get("preferredMoveIn"),preferredFloor:f.get("preferredFloor"),occupants:Number(f.get("occupants")),emergencyContact:f.get("emergencyContact"),notes:f.get("notes")}});setSubmitted(true)}catch(err){setError(err.message)}finally{setBusy(false)}}
  if(submitted)return <div className="center-page"><div className="card success-panel"><h2>Application submitted</h2><p>Your application is now waiting for Casa Vicenta admin review.</p><button className="btn primary" onClick={()=>onNavigate("home")}>Back to website</button></div></div>;
  return <div className="form-page"><div className="form-shell card"><div className="eyebrow">Applicant Form</div><h1>Apply for a room</h1><p className="muted">Fill out your details for review and viewing scheduling.</p>{error&&<div className="notice error">{error}</div>}<form onSubmit={submit} className="form-grid">
    <label>Full Name<input name="fullName" required placeholder="Juan Dela Cruz"/></label><label>Facebook<input name="facebook" required placeholder="Facebook name or profile link"/></label><label>Phone Number<input name="phone" required placeholder="09XXXXXXXXX"/></label><label>Occupation / School<input name="occupationSchool"/></label><label>Preferred Move-in Date<input name="preferredMoveIn" type="date"/></label><label>Preferred Floor<select name="preferredFloor" defaultValue="No Preference"><option>First Floor</option><option>Second Floor</option><option>No Preference</option></select></label><label>Number of Occupants<input name="occupants" type="number" min="1" defaultValue="1"/></label><label className="full-span">Emergency Contact<input name="emergencyContact" placeholder="Name and phone number"/></label><label className="full-span">Additional Notes<textarea name="notes" rows="4"/></label><label className="checkbox full-span"><input type="checkbox" required/> I confirm the information above is correct.</label><div className="full-span actions"><button type="button" className="btn secondary" onClick={()=>onNavigate("home")}>Cancel</button><button className="btn primary" disabled={busy}>{busy?"Submitting…":"Submit Application"}</button></div>
  </form></div></div>;
}
